@endpoint = http://localhost:8000
@username = becolem@microsoft.com

### Create a new player
POST {{endpoint}}/player
Content-Type: application/json
x-username: {{ username }}

{
  "name": "Joe Manpuncher",
  "class": "Barbarian",
  "description": "Very smelly"
}

### Get a player
GET {{endpoint}}/player
x-username: {{ username }}

### Delete a player
DELETE {{endpoint}}/player
x-username: {{ username }}

### Get player location
GET {{endpoint}}/player/location
x-username: {{ username }}

### Send command
POST {{endpoint}}/cmd
x-username: {{ username }}

{
  "text": "look"
}