@endpoint = http://localhost:8000

// Token with preffered username = becolem@microsoft.com
@jwt = THIS_IS_IGNORED.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJiZWNvbGVtQG1pY3Jvc29mdC5jb20ifQ.THIS_IS_IGNORED

### Create a new player
POST {{endpoint}}/player
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Joe Manpuncher",
  "class": "Barbarian",
  "description": "Very smelly"
}

### Get the player
GET {{endpoint}}/player
Authorization: Bearer {{ jwt }}

### Delete the player
DELETE {{endpoint}}/player
Authorization: Bearer {{ jwt }}

### Get player location
GET {{endpoint}}/player/location
Authorization: Bearer {{ jwt }}

### Send command
POST {{endpoint}}/cmd
Authorization: Bearer {{ jwt }}

{
  "text": "look"
}