@endpoint = http://localhost:8000
@username = test@test.com
#becolem@microsoft.com

### Create a new player
POST {{endpoint}}/player
Content-Type: application/json
x-username: {{ username }}

{
  "name": "Joe Manpuncher",
  "class": "Barbarian",
  "description": "Very smelly"
}

### Get a player
GET {{endpoint}}/player
x-username: {{ username }}

### Delete a player
DELETE {{endpoint}}/player
x-username: {{ username }}